name: serenity
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  neopop: ^1.0.2
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.4+1
  lottie: ^3.1.3
  flutter_launcher_icons: ^0.14.1
  neon_circular_timer: ^0.0.8
  flutter_tts: ^4.0.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  icons_launcher: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/playstore.png


icons_launcher:
  image_path: "assets/playstore.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true



# To add custom fonts to your application, add a fonts section here.
# Example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
